import BreadCrumb from "../../Components/BreadCrumb";
import { Fragment } from "react/jsx-runtime";
import { useState } from "react";
import { useDashboardContext } from "../../provider/DashboardContext";
import { Typography, Input, Select, Button, Skeleton, message } from "antd";
import {
  getVisualization,
  visualizationChoices,
} from "../../utils/data_visualization_choices";

const { Text } = Typography;
const { TextArea } = Input;

const CustomAnalyticalIndicatorPrimary = () => {
  const { generateIndicator } = useDashboardContext();
  const [messageApi, contextHolder] = message.useMessage();
  const [analysisGoal, setAnalysisGoal] = useState<string>("");
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [visualizationChoice, setVisualizationChoice] = useState<string>(
    visualizationChoices[0].value
  );

  return (
    <Fragment>
      {contextHolder}
      <BreadCrumb sidebarOption={{ label: "Custom Analytical Indicator" }} />
      <br />
      <section className="mb-2 ml-11">
        <h2 className="text-2xl font-semibold text-gray-700 mb-2">
          Disclaimer
        </h2>
        <ul className="space-y-1 list-disc list-inside text-gray-600">
          <li>
            This is an experimental feature for generating custom visualizations
            based on your analysis goal.
          </li>
          <li>
            Please be aware that the results generated by this tool might not be
            100% accurate and should be used on an experimental basis only.
          </li>
          <li>
            Please note that this tool can only respond to basic-level simple
            questions and only basic-level visualizations in the forms of bar
            charts, pie charts, line charts, area charts, scatter charts and
            tables are supported.
          </li>
        </ul>
      </section>
      <div
        className="
      pt-[43px] pr-[46px] pb-[39px] pl-[46px]
      mt-[35px] mb-[98px] ml-[45px]
      bg-[#ffff] rounded-[15px]
      "
      >
        {isLoading ? (
          <Skeleton active />
        ) : (
          <Fragment>
            <div className="grid gap-[58px]">
              <div className="flex gap-[41px] h-fit">
                <Text className="font-medium text-[16px]">Analysis Goal</Text>
                <TextArea
                  className="font-normal text-[14px] rounded-[5px] resize-none"
                  autoSize={{ minRows: 3 }}
                  placeholder="Enter your analysis goal here...
E.g. I need to see how many correct answers have been given to each tutorial"
                  value={analysisGoal}
                  onChange={(e: any) => setAnalysisGoal(e.target.value)}
                />
              </div>
              <div className="flex">
                <Text className="font-medium text-[16px]">
                  Visualization Choice
                </Text>
                <Select
                  className="w-full"
                  showSearch
                  onChange={(e: string) =>
                    setVisualizationChoice(
                      visualizationChoices.find((choice) => choice.value === e)!
                        .value
                    )
                  }
                  defaultValue={visualizationChoices[0].value}
                  options={visualizationChoices}
                />
              </div>
              <div className="flex gap-[70px]">
                <Text className="font-medium text-[16px] w-[66px]">
                  Preview
                </Text>
                <div className="w-full">
                  {getVisualization(visualizationChoice)}
                </div>
              </div>
            </div>
            <div className="flex justify-end mt-[50px]">
              <Button
                type="primary"
                className="rounded-[2px]"
                onClick={() => {
                  if (analysisGoal === "") {
                    messageApi.open({
                      type: "error",
                      content: "Please enter an analysis goal",
                    });
                  } else {
                    setIsLoading(true);
                    generateIndicator(analysisGoal, visualizationChoice);
                  }
                }}
              >
                Generate
              </Button>
            </div>
          </Fragment>
        )}
      </div>
    </Fragment>
  );
};

export default CustomAnalyticalIndicatorPrimary;
