import { config } from "dotenv";

config();

const AZURE_STORAGE_ACCOUNT_NAME: string = process.env.AZURE_STORAGE_ACCOUNT_NAME!;
const AZURE_STORAGE_CONTAINER_NAME: string = process.env.AZURE_STORAGE_CONTAINER_NAME!;
const AZURE_STORAGE_SAS_TOKEN: string = process.env.AZURE_STORAGE_SAS_TOKEN!;


export { AZURE_STORAGE_ACCOUNT_NAME, AZURE_STORAGE_CONTAINER_NAME, AZURE_STORAGE_SAS_TOKEN };